export const PLACES_PER_PAGE = 2;
export const END_REACHED_TRESHOLD = 0.5;
export const DEFAULT_LATITUDE_DELTA_FOR_PLACE = 0.0922;
export const DEFAULT_LONGITUDE_DELTA_FOR_PLACE = 0.0421;
export const DEFAULT_LATITUDE_DELTA = 100;
export const DEFAULT_LONGITUDE_DELTA = 100;
